### ISSUE TITLE
⚠️⚠️⚠️Project Update⚠️⚠️⚠️

### ISSUE THREAD

**Issue by cjdowner** [hyperdexapp/cryptocurrency-icons#136]
I won’t be updating this project any more. It’s free to a good home. Just comment below if you want me to transfer this repo.

Here’s my reasons:

- I’m too busy. I have a demanding job
- I don’t use the icons in any projects - so there’s no incentive for me to continue adding coins
- It’s anxiety inducing. I know I have too many open issues and I know I can’t get around to adding them
- I want to spend my free time with family, not adding coins
- This got out of hand. I started with some popular coins, now I’ve added hundreds
- The few donations have been sent have been very kind. But aside from that, it’s pretty thankless

**Comment by cjdowner** [comment]
Awesome! I'll keep this issue open to let people in other timezones see and decide before doing anything. I know that Hyperdex and Delta were two projects that were using these icons and relying on more so they would make sense.

**Comment by lukechilds** [comment]
Hi @cjdowner, thanks for you work on this!

Apologies, the recent increase in icon requests is probably our fault. We've been using your package as our official icon pack for HyperDEX and asking new currencies to be listed here if they want their icon included.

Totally understand your reasoning for not wanting to maintain this anymore, we'd be happy to take this over if it's becoming a bit of a burden.

@carsenk Thanks for the mention, if @cjdowner decides to transfer ownership of the project over to us then you're welcome to help us collaborate on it.

**Comment by svenlombaert** [comment]
Hi @cjdowner ,

Thanks for the hard work, you made a lot of our users happy 😉! Here at Delta we already forked your repo because we only use the black and colored SVG, we don't need any of the generated images. If there would be no one else that wants to maintain this repo in its current form, we would happily take over and adapt it to our needs.

**Comment by cjdowner** [comment]
Hey - sorry for the late reply, I've been mostly offline. Thanks for the interest in taking this on, I'd love to give this a good home!

@lukechilds, happy for me to transfer to you? Perhaps you can add everyone else as a contributor to the project.

Here for everyone, is the [Sketch](http://sketchapp.com) file that I've been using to create the icons.

[Coins.zip](https://github.com/cjdowner/cryptocurrency-icons/files/2106998/Coins.zip)

**Comment by razorsyntax** [comment]
Definitely let us know where this ends up!

**Comment by lukechilds** [comment]
@cjdowner Yeah sure, thanks for the source files.

Btw, there are still a few unclaimed bounties for icons from us, if you give us a KMD address we'd love to send you some funds as a thank you for your work so far.

**Comment by cjdowner** [comment]
Transfer to @lukechilds has now been initiated. It feels bittersweet, but I hope I can occasionally contribute the odd request in the future when I find myself with some downtime. 

Here's my KMD address, much appreciated Luke! `RWjifyBfkQ2Q6DiQVYHcQKPNY9oKMPWLDi`

**Comment by ArchimedesofSyracuse** [comment]
Thank you for the work that you have done.  These are fantastic.

Will @lukechilds leave it at this location or change it to a different one?  I was hoping they could create one for gincoin and modify vertcoin since it's showing as a solid green circle?

**Comment by lukechilds** [comment]
@ArchimedesofSyracuse it's now located at https://github.com/hyperdexapp/cryptocurrency-icons. GitHub will auto-redirect everything over to the new location.

Feel free to open issues about those currencies.

@cjdowner Thanks again, this is for your hard work: [`bf6967e09c85e88b9923d95e64ba1508ce66316d42d075fb400f335583411e91`](https://kmd.explorer.supernet.org/tx/bf6967e09c85e88b9923d95e64ba1508ce66316d42d075fb400f335583411e91)

**Comment by cjdowner** [comment]
@lukechilds Thanks so much. I'm really pleased you value this project - I'm totally confident it's in safe hands. 😄
