### ISSUE TITLE
New svg icons look greyed out/dull?

### ISSUE THREAD

**Issue by hugeprestigellc** [hyperdexapp/cryptocurrency-icons#145]
I don't know if I'm just imagining this but all of a sudden the SVG icons randomly look greyed out/dull? 

<img width="619" alt="screen shot 2018-07-02 at 3 11 42 pm" src="https://user-images.githubusercontent.com/33875309/42181826-3f6f1150-7e0a-11e8-8e5d-6500ba141704.png">

Was this done on purpose?

**Comment by lukechilds** [comment]
Oops, looks like this was accidentally introduced when the assets were optimised.

https://github.com/hyperdexapp/cryptocurrency-icons/commit/6e87d6666ff00d4ad4e3bcbc2cf58ed1c3b9d0f1

You can see the before after here:
https://github.com/hyperdexapp/cryptocurrency-icons/blob/a702f1cf8c7124f6770b732644a06bbc53fc1686/svg/icon/btc.svg

https://github.com/hyperdexapp/cryptocurrency-icons/blob/6e87d6666ff00d4ad4e3bcbc2cf58ed1c3b9d0f1/svg/icon/btc.svg

Will revert that commit now while we look into it. Thanks for reporting!

**Comment by lukechilds** [comment]
I've reverted that commit https://github.com/hyperdexapp/cryptocurrency-icons/commit/c1bb5a96eb3204a7e1a5baf308ee3d5cb8c4c8bc

The issue should be resolved now, thanks!

**Comment by sindresorhus** [comment]
I tracked this down to an issue in `svgcleaner`: https://github.com/RazrFalcon/svgcleaner/issues/163

**Comment by lukechilds** [comment]
Good detective skills! 🔍

**Comment by cjdowner** [comment]
This was something I actually encountered when optimising via SVGO. It seems to strip the blend mode which is applied to the gradient.

**Comment by sindresorhus** [comment]
@cjdowner The SVGO version bundled in ImageOptim seems to handle it fine.

**Comment by cjdowner** [comment]
@sindresorhus Right, my workflow used https://www.sketchapp.com/extensions/plugins/svgo-compressor/ Sketch plugin (which optimised on export) before I found the problem. But anyway, blend modes ☝️

**Comment by lukechilds** [comment]
It would also be worth looking at how much size optimising SVGs saves us versus how unreadable the output is.

If we only get like a 1% saving from an already tiny file but it makes the output totally unreadable, removes all indentation and renames all ids from something like `drop-shadow-1` to something like `a` then I don' think it's worth optimising them.
