### ISSUE TITLE
I would like to change the zilla icon to an enhanced version for BarterDEX

### ISSUE THREAD

**Issue by ptyx11** [hyperdexapp/cryptocurrency-icons#147]
We optimized the icon for barterdex colors
[zilla.svg.zip](https://github.com/hyperdexapp/cryptocurrency-icons/files/2164793/zilla.svg.zip)

**Comment by sindresorhus** [comment]
All the icons here follow certain guidelines. For example, white symbol.

**Comment by ptyx11** [comment]
I would still like to change it.

**Comment by ptyx11** [comment]
<img width="275" alt="screen shot 2018-07-07 at 8 34 13 pm" src="https://user-images.githubusercontent.com/32718517/42413629-76bd96f4-8224-11e8-85d1-9d9eee0e1c0e.png">
